#! /usr/bin/env python
## -*- coding: utf-8 -*-
#
# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

from snakemake.utils import min_version
from snakemake.exceptions import WorkflowError

min_version("6.4.1")

configfile: "config/config.yaml"

# rules 
include: "rules/felicitar_con_pastel.smk"

# rule all
rule all:
    input:
        expand("results/celebracion/felicitaciones_para_{persona}.pdf", persona = config['festejadx']['nombre'])

# actualmente solo festejamos a una persona (para que sea especial o asi jeje)
# como festejariamos a mas de una persona a lmismo tiempo?

