# this file contains everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples file that contains
# one row per sample that can easily be parsed e.g. via pandas

cumples_data:
    filename: "config/cumpleaneros_octubre.csv"
    nombre: "friend"
    fecha: "date_of_birth"
    color_pastel: "sabor"
    color_frosting: "frosting"

